Skip scanning the blockchain for new wallets
mintlayer/mintlayer-core pull request #1078
Opened 2023-07-24 20:54 UTC by OBorce

When a new wallet is created, we assume there are no used addresses and the scanning of the blockchain can be skipped.

2023-07-24 21:13 UTC, TheQuantumPhysicist approved these changes
Please make sure this works fine when restoring wallets. Meaning: Restored wallets will rescan the blockchain.

Usually the user is asked for the date, from which the scan should start, when a wallet is restored. While you don't have to implement that right now, please make sure it starts from 0 at least.

2023-07-25 05:32 UTC, muursh approved these changes

2023-07-26 16:58 UTC, TheQuantumPhysicist commented on wallet/src/account/mod.rs
> +    ) -> WalletResult<bool> {
Please explain in documentation what this does

2023-07-26 19:49 UTC, TheQuantumPhysicist commented on wallet/src/account/mod.rs
> +        let mut new_tx_was_added = false;
This is really ugly... can we do some mapping to make this more functional?

2023-07-26 19:52 UTC, TheQuantumPhysicist commented on wallet/src/account/mod.rs
> +    pub fn sync_best_block(
Please document this function.

I have a feeling this function name is not really indicative to what this function is doing... after you document it let's talk again about it.

2023-07-26 20:00 UTC, TheQuantumPhysicist commented on wallet/src/wallet/mod.rs
> +            next_unused_account,
Can you please explain why we need to track this? What has changed in this PR that necessitates it?

2023-07-26 20:01 UTC, TheQuantumPhysicist commented on wallet/src/wallet/mod.rs
> +        // scaning for addresses of the previous next unused account and it is not alowed to create a gap in
scanning
allowed

2023-07-26 20:01 UTC, TheQuantumPhysicist commented on wallet/src/wallet/mod.rs
> +        // scaning for addresses of the previous next unused account and it is not alowed to create a gap in
two typos

2023-07-26 20:15 UTC, TheQuantumPhysicist commented on wallet/src/wallet/tests.rs
> +    // as the new accout will be in sync by default we need to make it out of sync
account

2023-07-26 20:16 UTC, TheQuantumPhysicist requested changes
I have to say... all these changes just to avoid scanning from zero? Too much! We should have a discussion about this. Though this PR isn't a priority, to be clear.

2023-09-12 15:58 UTC, TheQuantumPhysicist commented
Done through gitlab.

2023-09-12 15:58 UTC, closed without merging