Introduce `PoSChainConfigBuilder` and change maturity distances for Testnet
mintlayer/mintlayer-core pull request #1250
Opened 2023-09-30 11:28 UTC by azarovh

The main goal for this PR is to change maturity distances for `Testnet` from 2000 to 7200 for both decommissioning and spending a share.  
But the way `PoSChainConfig` had been initialising was inconvenient so I added `PoSChainConfigBuilder`.

2023-10-02 15:27 UTC, TheQuantumPhysicist approved these changes

2023-10-02 15:33 UTC, TheQuantumPhysicist requested changes
As agreed, the builder should go to unit tests only to simplify, and there should not be defaults that specify complex consensus rules.

2023-10-04 10:59 UTC, TheQuantumPhysicist approved these changes

2023-10-04 19:58 UTC, muursh approved these changes

2023-10-05 06:41 UTC, iljakuklic approved these changes

2023-10-05 06:50 UTC, merged