chore: fix symbol error
mintlayer/mintlayer-core pull request #1811
Opened 2024-09-14 10:09 UTC by xixishidibei

2024-09-16 08:17 UTC, ImplOfAnImpl approved these changes
Thanks.

2024-09-16 13:49 UTC, azarovh requested changes
Please sign the commit with your [GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification).

2024-09-18 03:54 UTC, xixishidibei commented
> Please sign the commit with your [GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification).

Thanks. Signed.

2024-09-18 07:27 UTC, azarovh approved these changes

2024-09-18 10:50 UTC, merged